version: '3.7'

services:
  
  front:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    ports:
      - 8081:8081
      
  test:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/test.sh"]
    ports:
      - 8082:8082
      
  build:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/build.sh"]