version: '3.7'

services:
  
  api:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    ports:
      - 8081
      
  test:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/test.sh"]
    ports:
      - 5000:8081
      
  build:
    build: .docker/build/node
    volumes: 
      - ./:/usr/src/app/
    entrypoint: ["sh", "/usr/build.sh"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}